### ISSUE TITLE
Jw Player not working landscape mode ?

### ISSUE THREAD

**Issue by Anbu312** [jwplayer/jwplayer-sdk-ios-demo#18]
JwPlayer not working landscape mode.

**Comment by karimJWP** [comment]
Hi! Could you be more specific ? Is this a fullscreen problem ?

**Comment by Anbu312** [comment]
Hi KarimJWP

I have integrated Jw player in my application. My application supported portrait mode only video play controller only allow landscape mode. Landscape mode working iPhone version 9.1 above 9.1 version crash my application.

**Comment by karimJWP** [comment]
please contact support+sdk@jwplayer.com and file a bug report. Thank you :)

**Comment by vaishdolly13** [comment]
I am having the same issue. Please help.

**Comment by karimJWP** [comment]
@vaishdolly13 to properly debug we will need to you to contact support+sdk@jwplayer.com. They will provide you with a vanilla app using our sdk and will ask you to edit it with your settings and to include steps to reproduce your bug. This is very important because fullscreen relies on many  settings that are external to our SDK, such as supported interface orientations of the view controller. With that information we will be able to properly debug. Thanks :)
