### ISSUE TITLE
Invalid Argument Exception upon JWPlayerController Instantiation

### ISSUE THREAD

**Issue by mark-bragg** [jwplayer/jwplayer-sdk-ios-demo#23]
![viewcontroller](https://user-images.githubusercontent.com/15349627/27054754-e666a586-4f76-11e7-8a6f-82f0acd6dc52.png)
![stack trace](https://user-images.githubusercontent.com/15349627/27054757-e89b2142-4f76-11e7-8c07-7901df6cd78e.png)

When I run this app, the error seen in the stack trace is causing my app to terminate: "Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[JWConfig customPlayerJs]: unrecognized selector sent to instance 0x608000141ad0'"

I can't figure out why this is happening, any help will be greatly appreciated.

**Comment by karimJWP** [comment]
Hi Mark, what SDK version are you using ? ALso, does this happen when offline ?

**Comment by mark-bragg** [comment]
jwplayer-ios-sdk-2.7.3+26, and I get the same error when I run the program offline.

**Comment by karimJWP** [comment]
Hi @mark-bragg , were you able to get it to work ? We have added a safeguard against that method which will go out in the next release. 
I believe the crash may be caused by not having `-all_load` in the `other linker flags` section in the project's `build settings`. Please ensure the project is set-up following these [instructions](https://developer.jwplayer.com/sdk/ios/docs/developer-guide/intro/getting-started/)

**Comment by mark-bragg** [comment]
I was able to fix it, thank you
