### ISSUE TITLE
ios native how to play m3u8 playlist with HD button ? 

### ISSUE THREAD

**Issue by ahyong87** [jwplayer/jwplayer-sdk-ios-demo#24]
Hi,

How to play m3u8 playlist with HD Button ?

**Comment by karimJWP** [comment]
Hi @ahyong87 the HD button has been removed for m3u8 playlists because quality switching is better handled internally; this is Apple's recommended approach. We have introduced the property `bitRateUpperBound` to the `JWConfig`, which can be used to set the maximum bitrate level accessible during adaptive quality switching. In other words, quality switching happens automatically for m3u8 playlists based on the device's connectivity and ability to play smoothly, and an upper bound can be set to prevent automatically switching to a quality level that consumes an excessive amount of bandwidth.

If you wish to have the HD button display, you can load multiple `JWSource` objects in the `JWConfig`'s sources array.

Cheers!

**Comment by Allan-Nava** [comment]
Is possible to implement the quality from m3u8?
