### ISSUE TITLE
Not able to change the playlist items with SDK v3.6.3 

### ISSUE THREAD

**Issue by bluelabeldeveloper1** [jwplayer/jwplayer-sdk-ios-demo#69]
Previously we were using JWPlayer-SDK (2.8.1) and with that playlist is working properly but when we updated the SDK to 3.6.3, We are not able to change the playlist items of player. 

At 1st load audio/video is playing properly  but when we replace the playlist items with other according to app requirement then its not working with update SDK version. Everytime we are getting player in buffer state.

Here is some of the code:

**To create a player**
var item : JWPlaylistItem = JWPlaylistItem()
item.file = url
item.title = title
item.image = Imageurl
arrPlaylist.add(item)

let config : JWConfig = JWConfig()
config.playlist = arrPlaylist as NSArray as! [JWPlaylistItem]
self.player = JWPlayerController(config: config)

**To change the playlist items**
 if (self.player != nil)
            {
                self.StopPlaying()
            }
  self.player?.load(arrPlaylist as! [JWPlaylistItem])
  self.player?.playlistIndex = 0
  self.player?.delegate = self

Here arrPlaylist is having JWPlaylistItem objects.

**Comment by karimMourra** [comment]
Hi @bluelabeldeveloper1 , this issue was identified recently, has been fixed and will ship with 3.7.0. 
A minor suggestion based on your code sample: you do not need to reassign the delegate after calling `stop()`. The stop api simply sets the player to the idle state and offloads the current playlist item. Note that though the item is offloaded, the playlist is not modified. Calling play subsequently will restart the previous playlist.
