### ISSUE TITLE
React Native support

### ISSUE THREAD

**Issue by tanguyantoine** [jwplayer/jwplayer-sdk-ios-demo#9]
Did you plan to create a React native module to integrate easily your player inside React Native application?

**Comment by hblee** [comment]
We currently do not have any concrete plans for React Native at this time, but our mobile product & engineering team will be investigating and researching this opportunity to assess it's value to our native mobile SDKs.

We're certainly aware of the impact F8 had in energizing React Native and will be thoroughly evaluating it.

Thanks for asking!

Please feel free to use our [iOS Gitter room](https://gitter.im/jwplayer/jwplayer-sdk-ios-demo) for questions.

Closing this issue since no bug reported here.

**Comment by tanguyantoine** [comment]
Sorry for posting here but you twitter account seems to never respond to question. Can we imagine to let the community doing the react native bridge?

**Comment by scaryguy** [comment]
Currently I'm working on a React Native project and I'm trying to figure out how to use JWPlayer iOS SDK with it.

I would really appreciate if you'd share some thoughts and suggestions about the implementation to React Native...
